baseurl: "https://olymvis.netlify.app/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Post
      url: "post/"
      weight: 2

params:
  description: "Visualizing 120 years of Summer Olympics"
  footer: "&copy; [Hongtao Hao](https://hongtaoh.com), 2021"

markup:
  goldmark:
    renderer:
      unsafe: true
