baseurl: "https://olymvis.netlify.app/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: 数学 与 练字
      url: ""
      weight: 1
    - name: 英语
      url: "english/"
      weight: 2

    # - name: 练字
    #   rul: "cali/"
    #   weight: 3

params:
  description: "Visualizing 120 years of Summer Olympics"
  footer: "&copy; [Hongtao Hao](https://hongtaoh.com), 2021"

markup:
  goldmark:
    renderer:
      unsafe: true
